vocab:
  load_fpath: null
  save: true

dataset:
  csv_fpath: "VI_IMDB.csv"
  tokenized_fpath: null
  tokenized_save: true
  split_rate: 0.8

model:
  embedding_fpath: "vi_word2vec.txt"
  embedding_dim: 100
  hidden_dim: 256
  n_layers: 2
  bidirectional: true
  dropout: 0.5

train:
  n_epochs: 6
  batch_size: 100
  logs_dir: null
  save_epoch: 2

continue:
  state_fpath: null